services:
  - type: web
    name: dreamhubb-be-php
    env: docker
    plan: starter
    dockerContext: .
    dockerCommand:
      - /bin/sh
      - -lc
      - 'chmod +x ./start.sh && ./start.sh'
    autoDeploy: true
